name: Generate and deploy reports
permissions:
  contents: read
on: workflow_dispatch

jobs:
  run-reports:
    name: Generate reports
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ vars.BASE_NODE_VERSION }}
          cache: "npm"
      - id: cache-version
        run: echo "cachedate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - id: cache-odc-data
        uses: actions/cache@v4
        with:
          enableCrossOsArchive: true
          path: tmp/owasp/data
          key: odc-data-cache-${{ steps.cache-version.outputs.cachedate }}
          restore-keys: odc-data-cache-
      - run: npm ci
      - run: npm run build
      - run: npm run coverage
      - run: npm run owasp -- -f HTML --ossIndexUsername atwupack@mailbox.org --ossIndexPassword ${{ secrets.OSS_INDEX_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      - id: upload-reports
        uses: actions/upload-pages-artifact@v4
        with:
          path: reports
  deploy-reports-on-gh-pages:
    name: Deploy reports on GitHub pages
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.reports.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: run-reports
    steps:
      - name: Deploy reports to GitHub Pages
        id: reports
        uses: actions/deploy-pages@v4
